"""empty message

Revision ID: 0ad873169dec
Revises: 7a83f383a863
Create Date: 2024-12-19 15:04:32.852970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad873169dec'
down_revision = '7a83f383a863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_categories')
    op.drop_table('checklist_items')
    op.drop_table('checklist_templates')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('Health & Safety', 'Accident Reports', 'Fire Safety', 'HACCP', 'Allergen Information', 'Temperature Control Logs', 'Cleaning Records', 'Licenses and Permits', 'Staff Records', 'Operational Policies', name='doc_category'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('category')

    op.create_table('checklist_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=255), nullable=False),
    sa.Column('checklist_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
