"""empty message

Revision ID: 0e1dd1394b7e
Revises: 
Create Date: 2024-12-12 11:14:58.588005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1dd1394b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subusers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_subuser_manager', 'users', ['manager_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subuser_manager', type_='foreignkey')
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('subusers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=8), nullable=False),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='fk_subuser_manager', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
