"""empty message

Revision ID: 263848e94428
Revises: 2c98d92b42e1
Create Date: 2025-01-23 09:48:09.752337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263848e94428'
down_revision = '2c98d92b42e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('stripe_subscription_id')

    # ### end Alembic commands ###
