"""empty message

Revision ID: 29762c2b0156
Revises: f9eae4e443cc
Create Date: 2025-01-27 09:10:01.678803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29762c2b0156'
down_revision = 'f9eae4e443cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.String(length=255), nullable=True))
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###
