"""add user mixin

Revision ID: 371821f2b4b4
Revises: 9fe6a7918f9b
Create Date: 2024-12-10 07:07:51.585731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371821f2b4b4'
down_revision = '9fe6a7918f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_document_category', ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_document_category')

    # ### end Alembic commands ###
