"""empty message

Revision ID: 465c66edcea4
Revises: b66d816ad2c2
Create Date: 2024-12-12 13:47:25.741381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465c66edcea4'
down_revision = 'b66d816ad2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
