"""empty message

Revision ID: 55531d8dd9b3
Revises: 2ac5312f990b
Create Date: 2025-01-22 11:19:29.977481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55531d8dd9b3'
down_revision = '2ac5312f990b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
