"""empty message

Revision ID: 57b5db34be92
Revises: 4ef9c22f2f72
Create Date: 2024-12-21 09:35:50.796026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b5db34be92'
down_revision = '4ef9c22f2f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('restaurant_id',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('manager_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
