"""add is_active to user

Revision ID: 611224ad0b84
Revises: 371821f2b4b4
Create Date: 2024-12-10 09:12:43.557697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611224ad0b84'
down_revision = '371821f2b4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
