"""empty message

Revision ID: 7a83f383a863
Revises: d6b90f2b4da0
Create Date: 2024-12-18 10:30:05.898232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a83f383a863'
down_revision = 'd6b90f2b4da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('user_categories')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Enum('Health & Safety', 'Accident Reports', 'Fire Safety', 'HACCP', 'Allergen Information', 'Temperature Control Logs', 'Cleaning Records', 'Licenses and Permits', 'Staff Records', 'Operational Policies', name='doc_category'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('Health & Safety', 'Accident Reports', 'Fire Safety', 'HACCP', 'Allergen Information', 'Temperature Control Logs', 'Cleaning Records', 'Licenses and Permits', 'Staff Records', 'Operational Policies', name='doc_category'),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)

    op.create_table('user_categories',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
