"""add enum types for categories and user roles

Revision ID: 92b87504a55f
Revises: 
Create Date: 2024-12-09 07:36:32.271454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b87504a55f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('Hygiene', 'Health & Safety', 'Training', 'Licenses', name='doc_category'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('Hygiene', 'Health & Safety', 'Training', 'Licenses', name='doc_category'),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
