"""add user password functions

Revision ID: 9fe6a7918f9b
Revises: 92b87504a55f
Create Date: 2024-12-09 07:38:09.076887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe6a7918f9b'
down_revision = '92b87504a55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_restaurant', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('admin', 'sub-user', 'viewer', 'editor', name='user_roles'),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('user_restaurant', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'sub-user', 'viewer', 'editor', name='user_roles'),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
