"""empty message

Revision ID: b66d816ad2c2
Revises: 0e1dd1394b7e
Create Date: 2024-12-12 11:28:12.212988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66d816ad2c2'
down_revision = '0e1dd1394b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               nullable=True)
        batch_op.drop_constraint('fk_subuser_manager', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_subuser_manager', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('manager_id',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
