"""fix relationship issues

Revision ID: bf8fd4766475
Revises: 7e8dbd613248
Create Date: 2025-01-09 11:33:34.197314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8fd4766475'
down_revision = '7e8dbd613248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_restaurant', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=8), nullable=False))

    # ### end Alembic commands ###
