"""update doc categories enum types

Revision ID: dcea72d5aa4e
Revises: 611224ad0b84
Create Date: 2024-12-11 11:14:01.361057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcea72d5aa4e'
down_revision = '611224ad0b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('Hygiene', 'Health & Safety', 'Training', 'Licenses', 'Compliance', 'Documentation', 'Cleaning Records', 'inspection Records', 'Staff Records', name='doc_category'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('Hygiene', 'Health & Safety', 'Training', 'Licenses', 'Compliance', 'Documentation', 'Cleaning Records', 'inspection Records', 'Staff Records', name='doc_category'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
